### ISSUE TITLE
[Prod] : messages d'erreur à la création d'un offering

### ISSUE THREAD

**Issue by fdubreil** [ignf-sidc/ignf-gpf-api#90]
Commande lancée :

python -m ignf_gpf_api --debug --ini config-recette_prod.ini workflow -f admin-express.jsonc -s publication-wms-vecteur

Logs : 
----------------------------------------------------------------------------------------------
INFO - Ouverture du workflow /home/FDubreil/Developpements/ignf-gpf-api/admin-express.jsonc...
DEBUG - route_request(user_get, GET, None, None)
DEBUG - url_request(https://data.geopf.fr/api/users/me, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/users/me, GET, None, None)
INFO - Lancement de l'étape publication-wms-vecteur...
INFO - Résolution de l'action 'publication-wms-vecteur-0'...
DEBUG - route_request(configuration_list, GET, None, {'name': 'fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS', 'page': 1, 'limit': 10})
DEBUG - url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations, GET, {'name': 'fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS', 'page': 1, 'limit': 10}, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations, GET, {'name': 'fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS', 'page': 1, 'limit': 10}, None)
DEBUG - resolve_group - {store_entity.configuration.infos._id [INFOS(name=fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS)]} (store_entity : configuration.infos._id [INFOS(name=fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS)] => 746f9e77-f8b1-46fe-a5af-a08cee078fcc)
DEBUG - resolve_group - {store_entity.configuration.infos._id [INFOS(name=fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS)]} (from cache)
DEBUG - route_request(datastore_get, GET, None, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1, GET, None, None)
DEBUG - resolve_group - {store_entity.endpoint.infos._id [INFOS(type=WMS-VECTOR)]} (store_entity : endpoint.infos._id [INFOS(type=WMS-VECTOR)] => ae022611-13eb-4a18-8d04-9b7604a031cc)
DEBUG - resolve_group - {store_entity.endpoint.infos._id [INFOS(type=WMS-VECTOR)]} (from cache)
INFO - Résolution de l'action 'publication-wms-vecteur-0' : terminée
INFO - Exécution de l'action 'publication-wms-vecteur-0'...
INFO - Création d'une offre...
DEBUG - route_request(configuration_get, GET, {'configuration': '746f9e77-f8b1-46fe-a5af-a08cee078fcc'}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations/746f9e77-f8b1-46fe-a5af-a08cee078fcc, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations/746f9e77-f8b1-46fe-a5af-a08cee078fcc, GET, None, None)
DEBUG - route_request(configuration_list_offerings, GET, {'configuration': '746f9e77-f8b1-46fe-a5af-a08cee078fcc'}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations/746f9e77-f8b1-46fe-a5af-a08cee078fcc/offerings, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations/746f9e77-f8b1-46fe-a5af-a08cee078fcc/offerings, GET, None, None)
DEBUG - route_request(offering_create, POST, {'configuration': '746f9e77-f8b1-46fe-a5af-a08cee078fcc'}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations/746f9e77-f8b1-46fe-a5af-a08cee078fcc/offerings, POST, None, {'visibility': 'PUBLIC', 'endpoint': 'ae022611-13eb-4a18-8d04-9b7604a031cc'})
DEBUG - __url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/configurations/746f9e77-f8b1-46fe-a5af-a08cee078fcc/offerings, POST, None, {'visibility': 'PUBLIC', 'endpoint': 'ae022611-13eb-4a18-8d04-9b7604a031cc'})
DEBUG - route_request(offering_get, GET, {'offering': '901f3053-793b-45a1-b590-ff446707189d'}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/offerings/901f3053-793b-45a1-b590-ff446707189d, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/f2201719-549e-4fd0-a90e-ad859fe688d1/offerings/901f3053-793b-45a1-b590-ff446707189d, GET, None, None)
ERREUR FATALE - Erreur non spécifiée :
ERREUR - Traceback (most recent call last):
  File "/home/FDubreil/Developpements/ignf-gpf-api/ignf_gpf_api/__main__.py", line 331, in <module>
    main()
  File "/home/FDubreil/Developpements/ignf-gpf-api/ignf_gpf_api/__main__.py", line 57, in main
    workflow(o_args)
  File "/home/FDubreil/Developpements/ignf-gpf-api/ignf_gpf_api/__main__.py", line 320, in workflow
    o_workflow.run_step(o_args.step, lambda processing_execution: PrintLogHelper.print(processing_execution.api_logs()), behavior=s_behavior)
  File "/home/FDubreil/Developpements/ignf-gpf-api/ignf_gpf_api/workflow/Workflow.py", line 81, in run_step
    o_action.run()
  File "/home/FDubreil/Developpements/ignf-gpf-api/ignf_gpf_api/workflow/action/OfferingAction.py", line 34, in run
    s_urls = "\n   - ".join([d_url["url"] for d_url in o_offering["urls"]])
  File "/home/FDubreil/Developpements/ignf-gpf-api/ignf_gpf_api/workflow/action/OfferingAction.py", line 34, in <listcomp>
    s_urls = "\n   - ".join([d_url["url"] for d_url in o_offering["urls"]])
TypeError: string indices must be integers

ERREUR FATALE - Erreur non spécifiée.
---------------------------------------------------------------------------------------------------------

**Comment by fdubreil** [comment]
Le morceau de config utilisée :
```
// Étape n°7 : publication du flux WMS vecteur
            "publication-wms-vecteur": {
                "actions": [
                    {
                        "type": "offering",
                        "url_parameters" : {
                            "configuration": "{store_entity.configuration.infos._id [INFOS(name=fd_ADMIN-EXPRESS_%-%__SHP_%_%_%_WMS)
]}"
                        },
                        "body_parameters": {
                            "visibility": "PUBLIC",
                            "endpoint": "{store_entity.endpoint.infos._id [INFOS(type=WMS-VECTOR)]}"
                        }
                    }
                ],
                "parents": ["publication-wms-vecteur-validation"]
            }
```

**Comment by LudivineSchlegel** [comment]
reporté dans tuleap : https://ign.mytuleap.com/plugins/tracker/?aid=817

**Comment by vsasyan-ignf** [comment]
La branche est mergée, je ferme le ticket.
